In [1]:
#task1
import numpy as np

# Create an array of even integers from 30 to 70
even_integers = np.arange(30, 71, 2)

# Print the resulting array
print("Array of even integers from 30 to 70:")
print(even_integers)

Array of even integers from 30 to 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [2]:
# Generate an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)

# Print the resulting array
print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)

Array of 15 random numbers from a standard normal distribution:
[-1.25884056 -0.07726358 -1.78805393  0.70007694 -0.50128672 -0.88447117
  1.92590232 -0.55830759 -0.29895547  0.05030289  1.20514119  1.28695059
  0.42981783 -0.12726416  0.07935178]


In [3]:
# Create two matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Compute the cross-product of the two matrices
cross_product = np.cross(matrix1, matrix2)

# Print the result
print("Cross-product of the two matrices:")
print(cross_product)

Cross-product of the two matrices:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


In [4]:
# Create a square matrix
matrix = np.array([[4, 7],
                   [2, 6]])

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

# Print the result
print("Determinant of the matrix:")
print(determinant)

Determinant of the matrix:
10.000000000000002


In [5]:
# Create a 3x3x3 array with random values
random_array = np.random.rand(3, 3, 3)

# Print the resulting array
print("3x3x3 Array with random values:")
print(random_array)

3x3x3 Array with random values:
[[[0.78065743 0.17623338 0.6074451 ]
  [0.62337099 0.50765819 0.70567615]
  [0.23236462 0.93280239 0.89235642]]

 [[0.6779429  0.56041145 0.82417987]
  [0.67947014 0.56837436 0.97250704]
  [0.93954329 0.87009352 0.3093838 ]]

 [[0.17940902 0.8108896  0.32968481]
  [0.34717526 0.5310469  0.34776753]
  [0.310523   0.60169739 0.47662126]]]


In [6]:
# Create a 5x5 array with random values
random_array = np.random.rand(5, 5)

# Print the array
print("5x5 Array with random values:")
print(random_array)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

# Print the minimum and maximum values
print("\n Minimum value:", min_value)
print(" Maximum value:", max_value)

5x5 Array with random values:
[[0.77850803 0.29477819 0.08799782 0.93783638 0.21124201]
 [0.09718951 0.85502026 0.11538873 0.72932705 0.80016824]
 [0.89839509 0.38167578 0.99180201 0.50603256 0.18780982]
 [0.92135703 0.70504236 0.11161064 0.9493077  0.69229219]
 [0.66077559 0.66158969 0.38552921 0.49675881 0.28020913]]

 Minimum value: 0.08799781686287012
 Maximum value: 0.9918020067501201


In [7]:
# Create a sample 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the mean along the second axis (axis=1)
mean_values = np.mean(array, axis=1)

# Compute the standard deviation along the second axis (axis=1)
std_dev_values = np.std(array, axis=1)

# Compute the variance along the second axis (axis=1)
variance_values = np.var(array, axis=1)

# Print the results
print("Mean along the second axis:")
print(mean_values)

print("\nStandard deviation along the second axis:")
print(std_dev_values)

print("\nVariance along the second axis:")
print(variance_values)

Mean along the second axis:
[2. 5. 8.]

Standard deviation along the second axis:
[0.81649658 0.81649658 0.81649658]

Variance along the second axis:
[0.66666667 0.66666667 0.66666667]
